### ISSUE TITLE
create* mutation with "serial" column

### ISSUE THREAD

**Issue by Chuckatron** [graphile/graphile-build#192] opened 2018-03-07 16:21 UTC
I have a table with a "serial" id PK:
```
     Column     |          Type          | Collation | Nullable |                Default                 
----------------+------------------------+-----------+----------+----------------------------------------
 id             | integer                |           | not null | nextval('call_types_id_seq'::regclass)
 call_type_name | character varying(255) |           | not null | 
Indexes:
    "call_types_pkey" PRIMARY KEY, btree (id)
    "call_types_call_type_name_key" UNIQUE CONSTRAINT, btree (call_type_name)
Referenced by:
    TABLE "calls" CONSTRAINT "calls_type_fkey" FOREIGN KEY (type) REFERENCES call_types(id)
```
I am attempting the following mutation, I wish to supply the `callTypeName`, but allow the `id` to be assigned by the DB:
```
mutation {
  createCallType(
    input: {
      clientMutationId: "y",
      callType: {
        id: 3
        callTypeName: "567"
      }
    }
   ) {
    clientMutationId
  }
}
```
If I supply an id, all is well, but if I omit it, I get:
```
"message": "duplicate key value violates unique constraint \"call_types_pkey\""
```
If I supply `id: DEFAULT` I get:
```
Expected type Int, found DEFAULT.
```
I'm sure I'm doing something stupid, any pointers?

**Comment by benjie** [comment] 2018-03-07 16:28
I'm guessing the issue is that you've inserted explicit IDs into the database without updating your sequence counter, so when you leave it as default it tries to create a new value that's already taken.

Try:

```sql
  ALTER SEQUENCE call_types_id_seq RESTART WITH 1000;
```

(Assuming 1000 > `select max(id) from call_types`)

https://www.postgresql.org/docs/9.6/static/sql-altersequence.html

**Comment by benjie** [comment] 2018-03-07 20:35
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Closed by benjie** 2018-03-07 20:35 UTC

**Comment by Chuckatron** [comment] 2018-03-07 21:18
Well, that's embarrassing. Thanks very much for pointing that out, deeply disappointed I didn't think of that! Now working perfectly. Many apologies @benjie for wasting your time.

**Comment by benjie** [comment] 2018-03-07 21:21
No problem 👍
