### ISSUE TITLE
null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by bkonkle** [graphile/graphile-build#189] opened 2018-03-01 11:25 UTC
Related to this issue discussed on the `graphql_ppx` project: https://github.com/mhallin/graphql_ppx/issues/26

For fields with default values, `NULL` is sent across rather than `DEFAULT` or omitting the values. From the postgres log:

```sql
insert into "events"."event" (
  "id", "created_at", "updated_at", "name", "date", "event_type", "location", "description", "owner"
) values(
  NULL, NULL, NULL, $1, $2, $3, $4, $5, NULL) returning *
)
```

I wrote this tiny plugin to fix the issue in a very manual way:

```js
const {dissocPath, reduce, keys} = require('ramda')

/**
 * Strip out null values from fields with defaults
 */
exports.stripNullsFromDefaultFields = (builder) => builder.hook('GraphQLObjectType:fields:field',
  (field, {pgSql: sql}, {scope: {isRootMutation, fieldName}}) => {
    const entityFields = ['id', 'createdAt', 'updatedAt']

    const fieldNameMap = {
      createUser: entityFields,
      createEvent: entityFields,
    }

    if (!isRootMutation) {
      return field
    }
    if (keys(fieldNameMap).includes(fieldName)) {
      const defaultResolver = obj => obj[fieldName]
      const {resolve: oldResolve = defaultResolver, ...rest} = field

      return {
        ...rest,
        resolve: function (root, input, context, ast) {
          const newInput = reduce(
            // Remove each field from the object
            (result, field) => dissocPath(['input', 'event', field], result),
            // Use the input as the initial accumulator
            input,
            // Remove the fields from the map above for the current field name
            fieldNameMap[fieldName]
          )

          const newAst = reduce(
            (result, field) => dissocPath(['variableValues', 'input', 'event', field], result),
            ast,
            fieldNameMap[fieldName]
          )

          return oldResolve(root, newInput, context, newAst)
        },
      }
    }
    return field
  }
)
```

Is there a way to solve this for all fields with default values, though?

Thanks for maintaining/expanding such an outstanding project!

**Comment by benjie** [comment] 2018-03-01 12:37
If you want to use the defaults simply don't specify that you want the column value to be null - if you specify null then we take you at your word. This is the same behaviour as SQL.

e.g.

```graphql
mutation CreateEvent($name: String!, date: Date!) {
  createEvent(input: {event: {name: $name, date: $date}}) {
    ...
  }
}
```

**Comment by bkonkle** [comment] 2018-03-01 14:32
@benjie According to @leebyron in [this thread](https://github.com/graphql/graphql-js/issues/133):

>In GraphQL input variables, there is no difference between null and undefined. The value null means "lack of a value".

It sounds like your understanding of this is different?

**Comment by bkonkle** [comment] 2018-03-01 14:38
It sounds like `postgraphile` should only be sending `null` to Postgres when it receives a `NullValue` scalar, rather than a primitive `null` - or, am I misunderstanding?

**Comment by benjie** [comment] 2018-03-01 14:58
A `NullValue` scalar in GraphQL specification speak is a primitive `null` in JSON (which is what we communicate with); read [this comment](https://github.com/graphql/graphql-js/issues/133#issuecomment-132792662) regarding omitting the key from the dictionary/map that represents the input value.

To the best of my knowledge PostGraphile's behaviour is correct in this regard. Besides changing the behaviour would be a breaking change and it would violate the Principle of Least Astonishment given it maps a PostgreSQL database which works in the same way (omit the value to use the default, specify `NULL` if you want to override the default with an explicit null value) and changing it would reduce the expressiveness and functionality of the system. Ultimately passing `{"a": 1"}` vs `{"a": 1, "b": null}` to `createEvent` express different things - the latter is explicitly saying that b should be set to null, whereas the former has no information on `b` so it should be left as its default value.

I can totally relate to your issue though! I believe the issue is that your mapper is dealing with the input value as if it were a concrete type with fixed keys and values. Really it's a dictionary with a whitelist of keys and types those keys can be, but where every non-nullable key is optional (the entries in the dictionary itself are optional - not just the values).

I hope you can find an acceptable solution - if you do I'd really appreciate it if you could share it here.

Good luck!

**Comment by bkonkle** [comment] 2018-03-01 15:33
Thank you so much for the detail! This is very helpful. I'll go back to the author of `graphql_ppx`, the library generating the input mappers.

**Comment by leebyron** [comment] 2018-03-01 18:31
Just to follow up - it’s correct that graphql should interpret an explicit null differently from an implicit missing value. That thread linked above walks through the decision making process from a couple years ago. We actually amended the spec to account for this as a result.

**Comment by benjie** [comment] 2018-03-07 20:35
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Closed by benjie** 2018-03-07 20:35 UTC
Labels: question
