### ISSUE TITLE
`getTypeByName` does not seem to work anymore

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-build#112] opened 2017-10-30 23:35 UTC
I supposed this is a related to the statement “The internals for types now work slightly differently; if you've written any plugins this may be problematic for you - reach out and I'll help you update to the new syntax (it's not too hard!)” statement on the [PostgraphQL V4 thread](https://github.com/postgraphql/postgraphql/pull/506#issuecomment-340274744)

I managed to replace its usage with some introspection and `pgGetGqlTypeByTypeId` but now I don’t know how to solve this part: I am adding a mutation manually and I want to reuse an existing input type but `getTypeByName(pgInflection.inputType("page"))` returns `undefined`

however, if I try to manually build a `GraphQLInputObjectType` like so:

```js
page: {
	type: new GraphQLNonNull(new GraphQLInputObjectType({
		name: pgInflection.inputType("page"),
		fields: {
			page_url: { type: new GraphQLNonNull(GraphQLString) },
			page_canonical_url: { type: GraphQLString },
			page_keywords: { type: new GraphQLList(new GraphQLNonNull(GraphQLString)) },
		},
	})),
}
```

It throws an error:

> Error: Schema must contain unique named types but contains multiple types named "PageInput".

So the type does exists but I can’t get it back with `getTypeByName`. Is it intended or is `getTypeByName` currently broken ? If it’s intended, should I try to get it with `pgGetGqlTypeByTypeId` instead ?

**Comment by chadfurman** [comment] 2017-10-31 11:46
Not sure why you'd use ```gettTypeByName(pgInflection.inputType("page"))`
```
and not simply:
```
getTypeByName("PageInput")```

**Comment by mathroc** [comment] 2017-10-31 15:40
maybe the example did not have enough context, here is what I’m trying to do:

```js
const postgraphile = require("./postgraphile");
const sql = require ("pg-sql2");

module.exports = function BeeSquadMutations(builder, {pgInflection}) {
	builder.hook("GraphQLObjectType:fields", (
		fields,
		{
			extend,
			findGqlTableType,
			gql2pg,
			graphql: {GraphQLNonNull, GraphQLID, GraphQLString, GraphQLList},
		},
		{scope: {isRootMutation}, fieldWithHooks}
	) => {
		if (!isRootMutation) {
			return fields;
		}

		return extend(fields, {
			CreateDiscussion: fieldWithHooks("CreateDiscussion", postgraphile.fieldSpec({
				spec: {
					type: new GraphQLNonNull(findGqlTableType("discussion")),
					args: {
						content: { type: new GraphQLNonNull(GraphQLString) },
						page: {
							type: new GraphQLNonNull(getTypeByName(pgInflection.inputType("page"))),
						}
					},
				},
				table: sql.identifier("graphql", "discussion"),
				resolvedData: async ({content, page: {url, canonical_url = null, keywords = []}}, {session, streams}) => {
					// [snip]
				},
			}, gql2pg)),
		});
	});
};
```

I could use `getTypeByName("PageInput")`, it’s exactly the same as `getTypeByName(pgInflection.inputType("page"))`, `getTypeByName` returns `undefined`.

so I’m not updating an existing type, I’m building a new one, and in it I’d like to reuse an existing one

in other places I’ve done some filtering on `introspectionResultsByKind.class` to find the `type.id` to call `pgGetGqlTypeByTypeId` but I don’t if I can find one for an input type

**Comment by benjie** [comment] 2017-10-31 17:28
I suspect the issue is that the type has not been defined at the time that you request it because they're now lazily evaluated. Though it could be just that I forgot to add the `addType` call somewhere and never realised.

Try using `pgGetGqlTypeByTypeId` (you can find the type id from the introspection results) for the Page table/view/whatever BEFORE calling getTypeByName.

Or try adding your plugin later so the type definitely exists first.

Or tell me that I forgot the `addType` call if that's the case ;)

GL!

**Comment by benjie** [comment] 2017-10-31 17:31
To be clear above - getting the type with `pgGetGqlTypeByTypeId` of the *base* type `Page` also registers other types at the moment.

Though in this case I think you might be after `pgGetGqlInputTypeByTypeId`

**Comment by mathroc** [comment] 2017-11-01 02:16
it seems odd that `getTypeByName` would return `undefined` and that trying to register the `PageInput` type throws :
> Error: Schema must contain unique named types but contains multiple types named "PageInput".

the plugin is actually added after all other default plugins

I’m going to try it with `pgGetGqlInputTypeByTypeId` and also see if `getTypeByName` works once I got it with `pgGetGqlInputTypeByTypeId`

**Comment by mathroc** [comment] 2017-11-01 03:30
so I managed to get the input type with `pgGetGqlInputTypeByTypeId`, thx @benjie 
and after that `getTypeByName` for this type also worked. so even though the plugin was in last position I cannot use `getTypeByName`.

If this is expected you can close this issue

**Comment by benjie** [comment] 2017-11-01 08:24
You can use DEBUG=“graphile*” envvar to see the order the various hooks are executing in which should give you a better understanding of what’s going on. Please report back 👍

**Comment by msand** [comment] 2017-11-01 09:03
I'm trying to achieve a bit similar thing. I have a pg stored proc for multi-table (substance and recipe) search, I have defined a SearchResult table structure with foregin keys for the results {substanceId, recipeId} to allow traversing the relation, and have the substanceBySubstanceId and recipeByRecipeId resolvers generated automatically, this work correctly.

I have now set up elasticsearch and made a graphile plugin to return the same structure and reuse the resolvers. But, the substanceBySubstanceId and recipeByRecipeId keep returning null, @benjie you have any insight why? Or should I just dive into the library and resolution logic?

```js
const search = require("./search");

module.exports = function ElasticSearchPlugin(builder) {
  builder.hook("GraphQLObjectType:fields", (
    fields,
    build,
    { scope: { isRootQuery } } // Context object - used for filtering
  ) => {
    if (!isRootQuery) {
      // This isn't the object we want to modify:
      // return the input object unmodified
      return fields;
    }

    const {
      extend,
      getTypeByName,
      graphql: { GraphQLNonNull, GraphQLString, GraphQLList }
    } = build;

    const SearchResult = getTypeByName("SearchResult");

    return extend(fields, {
      esSearch: {
        description: `Searches in ElasticSearch`,
        type: new GraphQLList(SearchResult),
        args: {
          query: {
            type: new GraphQLNonNull(GraphQLString)
          },
          index: {
            type: GraphQLString
          }
        },
        resolve: search
      }
    });
  });
};
```

**Comment by benjie** [comment] 2017-11-01 09:29
@msand I think that's a completely different thing since you're effectively trying to replace the resolver with one from a different source.

To make it work you need to ensure your data is returned in the right format. I believe the connection should resolve to an object with the following keys:

- `data` - an array of results
- `hasNextPage` - boolean
- `hasPreviousPage` - boolean
- `totalCount` - int

where each result has the GraphQL aliases of the fields requested plus `__cursor` containing the cursor. (I can't remember what the shape of the cursor is on the PG side.)

However because PostGraphile resolves each root field to just one query (no matter how deep the fields are) your resolver will need to do the same. This is something I intend to improve over time (i.e. make it so that a Postgres field can take over from a non-postgres field) but I haven't spent any time on that right now - you may be better off achieving it by stitching your PostGraphile schema together with an elastic search schema using something like `graphql-weaver`.

**Comment by msand** [comment] 2017-11-01 09:37
@benjie Thanks! I'm actually trying to make them available side-by-side, to be able to compare the relevance ranking, the common part is that they return results of the same data type / shape { substanceId, recipeId } (both bigint).
But I see now that stitching makes more sense because of the current single root query constraint in postgraphile, its great for getting efficient pg queries. Stitching should achieve all our current needs, efficiently enough anyway.

**Comment by msand** [comment] 2017-11-01 17:10
@benjie your suggested solution using graphql-weaver works its magic ;)
Had to add this to get the link to work correctly:
helpers:
```js
const base64 = str => new Buffer(String(str)).toString("base64");
const toNodeId = (...args) => base64(JSON.stringify(args));
```
and in the returned objects of the resolver:
```js
{
      ..._source,
      substanceBySubstanceId: toNodeId("substances", substanceId),
      recipeByRecipeId: toNodeId("recipes", recipeId)
}
```
and in the weaver conf:
```js
    {
      namespace: "es",
      typePrefix: "Es",
      schema: esSchema,
      fieldMetadata: {
        "SearchResult.substanceBySubstanceId": {
          // Field substance in type search
          link: {
            field: "k2.substance", // field substance in namespace k2
            argument: "nodeId", // argument of k2.substance
          }
        },
        "SearchResult.recipeByRecipeId": {
          // Field recipe in type search
          link: {
            field: "k2.recipe", // field recipe in namespace k2
            argument: "nodeId", // argument of k2.recipe
          }
        }
      }
    }
```

**Comment by benjie** [comment] 2017-11-01 17:25
Thanks for sharing @msand! 👍

**Comment by msand** [comment] 2017-11-01 17:50
Thank you! @benjie and @calebmer Without your wonderful contributions this wouldn't be nearly as great! :)
Couldn't thank you guys enough!

**Comment by benjie** [comment] 2017-11-29 19:44
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Comment by benjie** [comment] 2017-11-29 19:44
(This is not the DX I ultimately want, but that's something we're going to have to hone after we've released v4 I think.)

**Closed by benjie** 2017-11-29 19:44 UTC
