### ISSUE TITLE
Plugin to expose shortcuts for nested relations?

### ISSUE THREAD

**Issue by pepijnverburg** [graphile/graphile-build#214] opened 2018-04-29 13:16 UTC
Hi there, 

First of all great work on this amazing library. We are currently exploring how we can extend the plugins to support shortcuts for nested relations.

For example, take the following:
```
create table person (
  id uuid primary key,
  name varchar not null,
);

create table post (
  id uuid primary key,
  title text not null,
  body text,
  person_id uuid references person (id)
);

create table comments (
  id uuid primary key,
  body text,
  rating integer,
  post_id uuid references post (id)
);
```

Normally to get all the comments sent to each person one would:
```
{
  allPersons {
    nodes {
      id
     name

      postsByPersonId {
        id
        title
        body

        commentsByPostId {
          nodes {
            body
            rating
          }
        }
      }
    }
  }
}
```

Question is if we can efficiently generate shortcuts like this (semantically this example is questionable, as these are comments from other people):
```
{
 allPersons {
   nodes {
     id
     name

     # instantly get all comments other people gave on this person
     # including the pagination parameters!
     commentsByPersonId (first : 10) {
       nodes {
         body
         rating
       }
     }
   }
 }
}
```

We have been testing this by creating a _custom_ field for each of the possible paths, but when the schema gets more extensive maintainability drops significantly. It would be efficient to re-use the existing backward and forward relationship plugins to do the above by tying them together when nested relations are found. An automatic leveler can then be used to flatten the object in order to get rid of the nesting in the end result (e.g. https://github.com/chasingmaxwell/graphql-leveler). 

Are there already plans on adding this and to what extend are the existing plugins re-usable? We are more than happy to assist in such an plugin when there are some concrete starting points.

**Comment by benjie** [comment] 2018-04-29 16:10
I think this might be a duplicate of https://github.com/graphile/postgraphile/issues/91 - i.e. you’re wanting a way to do many/many relationships. This is on my todo list but it’s not near the top. Plan is to make fields on the join table available on the “edges” too. Currently the best way of achieving this is via a computed column which isn’t much effort at all really, but would be nice to have first-class support.

**Comment by benjie** [comment] 2018-04-29 16:13
Another issue is there’s loads of potential many-many relationships and we don’t necessarily want them all exposed, current thoughts on this are to use smart comments to say things like “@hasMany comments” to select to expose them. Haven’t got far down this line of thinking but it might be modelled on ActiveRecord?

**Comment by pepijnverburg** [comment] 2018-04-29 17:53
Thanks for the reply! But I think you misinterpret the question as it is not about many-to-many relationships, but about _nested relationships_ (consisting of either one-to-one and/or one-to-many relationships). 

Let me explain through a simple example: 1 Person has 5 Posts and each post has 10 Comments (not a many-to-many!). Now from the Person model we would like to directly get all the comments available without the need of first going through all the Post model layer. 

So instead of:
```
personById(id : '38483') {
  # results in 1 person row

  getPostsByPersonId {
    # results in 5 post rows

    getCommentsByPostId {
       # results in 10 comment rows for each of the posts
    }
  } 
}
```

We would be able to:
```
personById(id : '38483') {
   # results in 1 person row

    getCommentsByPersonId {
      # results directly in 50 comment rows (we don't care from which posts they came from)
    }
}
```

We've been thinking about using Fragments make these 'shortcuts', but this doesn't support specification of the fields you want to expose and does not support flattening / leveling of the result. An example of such a fragment would be:
```
fragment getCommentsByPersonId($first: Int = 100) on Person {
  getPostsByPersonId {
    id
    title
    getCommentsByPostId {
       id
       rating
    }
  }   
}
```
However, the end result is a nested object:
```
[{
  id: <id-of-post>,
  title: <title-of-post>
  getCommentsByPostId : [{
    id: <id-of-comment>,
    rating: <rating-of-comment>
  }, ...] // repeats 10 times
}, ...] // repeats 5 times
```
Instead of a flattened / leveled object (because we don't care about the Post model / middle layer):
```
getCommentsByPersonId : [{
   id: <id-of-comment>,
   rating: <rating-of-comment>
}, ...] // repeats 50 times
```
In practice such a plugin might be able to create a nested where-clause to directly get all the comments given on the posts of a specific user. For example to resolve the ```getCommentsByPersonId``` the following query could be generated:
```
SELECT * FROM comments
WHERE post_id IN (
  SELECT id FROM posts
  WHERE person_id = 38483
)
```
Another possibility is to utilize the existing backward and forward relationship plugins to first fetch the comments for each post and then merge them into 1 result. For this example meaning: from 5 Posts with 10 Comments to one list with 50 Comments.

**Comment by benjie** [comment] 2018-04-29 19:49
Another solution would be to denormalise the person_id onto the comments then you could do commentsByPersonId directly without requiring any plugins etc; it’d also be more performant as it would be a direct index lookup rather than a join.

**Comment by benjie** [comment] 2018-08-16 12:35
Denormalization is the recommended way of achieving this 👍

**Closed by benjie** 2018-08-16 12:35 UTC
Labels: enhancement, smart-comments?
